[project]
name = "django-ninja-crudl"
version = "0.2.3"
description = "CRUDL REST API endpoints from Django ORM models using Django Ninja framework"
requires-python = "==3.12.*"
authors = [{ name = "Jukka Hassinen", email = "jukka.hassinen@gmail.com" }]
license = "MIT"
readme = "README.md"
keywords = ["Django", "Ninja", "REST", "API", "CRUD", "CRUDL", "OpenAPI"]

classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Programming Language :: Python :: 3.12",
    "Framework :: Django :: 5.1",
    "Framework :: Pydantic :: 2",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

dependencies = [
    "django2pydantic",
    "django>=5.1.3",
    "django-ninja-extra>=0.21.4",
    "beartype>=0.19.0",
    "typeguard>=4.4.1",
    "django-stubs-ext>=5.1.1",
]

[dependency-groups]
dev = [
    "basedpyright>=1.21.0",
    "debugpy>=1.8.8",
    "django-stubs>=5.1.1",
    "hypothesis>=6.118.0",
    "import-linter>=2.1",
    "ipykernel>=6.29.5",
    "isort>=5.13.2",
    "mypy>=1.13.0",
    "nox>=2024.10.9",
    "nplusone>=1.0.0",
    "pydantic>=2.9.2",
    "pylint>=3.3.4",
    "pylint-django>=2.6.1",
    "pyre-check>=0.9.23",
    "pyright>=1.1.388",
    "pytest>=8.3.3",
    "pytest-cov>=6.0.0",
    "pytest-django>=4.9.0",
    "pytest-instafail>=0.5.0",
    "pytest-testmon>=2.1.1",
    # TODO(phuongfi91): pytype causes issue with overlapping ninja packages
    #    "pytype>=2024.10.11",
    "rich>=13.9.4",
    "ruff>=0.7.3",
    "schemathesis>=3.38.5",
    "wemake-python-styleguide>=0.19.2",
    "semgrep>=1.85.0",
    "nitpick",
    "django-stubs-ext>=5.1.1",
    "django-stubs[compatible-mypy]>=5.1.1",
    "beartype>=0.19.0",
    "typeguard>=4.4.1",
    "wemake-python-styleguide>=1.0.0",
    "taplo>=0.9.3",
    "project-config>=0.9.7",
    "pre-commit>=4.1.0",
    "python-semantic-release>=9.14.0",
    "watchfiles>=1.0.5",
]

[tool.uv.sources]
django2pydantic = { git = "https://github.com/NextGenContributions/django2pydantic", branch = "main" }
nitpick = { git = "https://github.com/NextGenContributions/nitpick", branch = "develop-ng" }

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple"
explicit = true

[project.urls]
Homepage = "https://github.com/NextGenContributions/django-ninja-crudl"
Documentation = "https://github.com/NextGenContributions/django-ninja-crudl/blob/main/README.md"
Repository = "https://github.com/NextGenContributions/django-ninja-crudl.git"
Issues = "https://github.com/NextGenContributions/django-ninja-crudl/issues"
Changelog = "https://github.com/NextGenContributions/django-ninja-crudl/blob/main/CHANGELOG.md"
"Release Notes" = "https://github.com/NextGenContributions/django-ninja-crudl/releases"
Funding = "https://github.com/sponsors/NextGenContributions"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.semantic_release]
assets = []
build_command_env = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
allow_zero_version = true
no_git_verify = false
tag_format = "v{version}"
version_toml = ["pyproject.toml:project.version"]
version_variables = [
    "django_ninja_crudl/__init__.py:__version__",
    "uv.lock:\"django-ninja-crudl\"\\nversion",
]

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.changelog]
exclude_commit_patterns = [
    '''chore(?:\([^)]*?\))?: .+''',
    '''ci(?:\([^)]*?\))?: .+''',
    '''refactor(?:\([^)]*?\))?: .+''',
    '''style(?:\([^)]*?\))?: .+''',
    '''test(?:\([^)]*?\))?: .+''',
    '''build\((?!deps\): .+)''',
    '''Merged? .*''',
    '''Initial Commit.*''',
    # Old semantic-release version commits
    '''^\d+\.\d+\.\d+''',
]
mode = "init"
insertion_flag = "<!-- version list -->"
template_dir = "templates"

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG.md"
output_format = "md"
mask_initial_release = false

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = false

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"

[tool.semantic_release.commit_parser_options]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
allowed_tags = [
    "feat",
    "fix",
    "perf",
    "build",
    "chore",
    "ci",
    "docs",
    "style",
    "refactor",
    "test",
]
default_bump_level = 0

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false
insecure = false

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true
